# 2- Column types: `repos`

In [1]:
import sys
sys.path.append("..")

from HelperFunctions.HelperFunctions_Explore.InspectTypes_Helper import table_types
from HelperFunctions.HelperFunctions_Explore.Stats import table_stats

In [2]:
table_types("repos")

,column,types found
0,full_name,"path (11,841)"
1,owner,"text (11,823), number (18)"
2,stars,"int (11,804), null (37)"
3,forks,"int (11,804), null (37)"
4,is_fork,"int (11,804), null (37)"
5,language,"text (11,113), empty (691), null (37)"
6,license,"empty (6,294), text (5,510), null (37)"
7,description,"text (7,077), null (4,752), filename (6), path (5), number (1)"
8,created_at,"timestamp (11,804), null (37)"
9,pushed_at,"timestamp (11,804), null (37)"
10,metadata_fetched,"int (11,841)"

## Numeric column stats

In [3]:
table_stats("repos")

             column  count  nulls  min     max  median  average
0             stars  11804     37    0  196579     0.0   234.14
1             forks  11804     37    0   59339     0.0    33.52
2           is_fork  11804     37    0       0     0.0     0.00
3  metadata_fetched  11841      0    1       1     1.0     1.00